#!/bin/bash

set -euo pipefail

if [[ $# -eq 0 ]]; then
    echo "Specify the Minecraft Mainline Server Version or "latest" for the latest version. If it ends in "-forge" then the forge server will be built"
    exit 0
fi

VERSIONS_JSON="https://launchermeta.mojang.com/mc/game/version_manifest.json"
FORGE_VERSIONS_JSON="http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json"

VERSION_TAG=$1

if [[ $VERSION_TAG == *-forge ]]; then
    MAINLINE_VERSION=${VERSION_TAG%-forge}
    forge="true"
else
    MAINLINE_VERSION="$VERSION_TAG"
    forge=""
fi

if [[ $MAINLINE_VERSION == "latest" ]]; then
    MAINLINE_VERSION=$(curl -fsSL $VERSIONS_JSON | jq -r '.latest.release')
fi

echo "Checking the version ..."
# check if the version is valid for the mainline server (prereq for forge as well)
MAINLINE_URL=$(curl -s $VERSIONS_JSON | jq --arg VERSION "$MAINLINE_VERSION" --raw-output '[.versions[]|select(.id == $VERSION)][0].url')
if [[ "$MAINLINE_URL" == "null" ]]; then
   echo "No such version $MAINLINE_VERSION for the mainline server. Available options: $(curl -s $VERSIONS_JSON | jq -r '.versions[]|.id' | tr '\n' ' ')"
   exit 1
fi

# check if the forge version for this serevr exists
if [[ $forge ]]; then
#    FORGE_VERSION=$(curl -fsSL $FORGE_VERSIONS_JSON | jq -r ".promos[\"$MAINLINE_VERSION-recommended\"]")
#    if [ $FORGE_VERSION = null ]; then
        FORGE_VERSION=$(curl -fsSL $FORGE_VERSIONS_JSON | jq -r ".promos[\"$MAINLINE_VERSION-latest\"]")
        if [ $FORGE_VERSION = null ]; then
            FORGE_SUPPORTED_VERSIONS=$(curl -fsSL $FORGE_VERSIONS_JSON | jq -r '.promos| keys[] | rtrimstr("-latest") | rtrimstr("-recommended")' | sort -u | tr '\n' ' ')
            echo "Version $MAINLINE_VERSION is not supported by Forge. Supported versions are $FORGE_SUPPORTED_VERSIONS"
            exit 2
        fi
#    fi
else
    FORGE_VERSION="noforge" # invalidate the location. It will be checked in the Dockerfile during the build
fi

echo "Preparing the context..."

if [[ $forge ]]; then
    verfolder=".build-cache/server-$MAINLINE_VERSION-forge"
    mkdir -p $verfolder
    cd $verfolder
    ../../download-forge-server.sh $MAINLINE_VERSION
else
    verfolder=".build-cache/server-$MAINLINE_VERSION"
    mkdir -p "$verfolder/libraries"
    cd $verfolder
    ../../download-minecraft-server.sh $MAINLINE_VERSION
fi

cd ../..
cp -a minecraft-server.sh "$verfolder"

# use dynamic tagging to switch base images
version_slug=$(echo $MAINLINE_VERSION | cut -d . -f 2)
if [[ $version_slug -le 16 ]]; then
    docker pull openjdk:8-jre-alpine
    docker tag openjdk:8-jre-alpine java-base-image
elif [[ $version_slug -le 17 ]]; then
    docker pull openjdk:16-alpine
    docker tag openjdk:16-alpine java-base-image
elif [[ $version_slug -lt 21 ]]; then
    docker pull openjdk:17-alpine
    docker tag openjdk:17-alpine java-base-image
else
    docker pull azul/zulu-openjdk-alpine:21-latest #openjdk:21-slim
    docker tag azul/zulu-openjdk-alpine:21-latest java-base-image
fi

docker build $verfolder -f ./Dockerfile -t alexivkin/minecraft-server:$VERSION_TAG --build-arg FORGE_INSTALLER="forge-$MAINLINE_VERSION-$FORGE_VERSION-installer.jar"

if [[ $VERSION_TAG == latest* ]]; then
    # add a tag with the actual version
    if [[ $forge ]]; then
        docker tag alexivkin/minecraft-server:$VERSION_TAG alexivkin/minecraft-server:$MAINLINE_VERSION-forge
    else
        docker tag alexivkin/minecraft-server:$VERSION_TAG alexivkin/minecraft-server:$MAINLINE_VERSION
    fi
fi

#rm -rf $verfolder
echo "done"
